#!/bin/sh

test $# -ne 1 && {
	echo "usage: $0 argnum" >&2
	exit 1;
}

max=$1

echo "/* This was autogenerated by $0 $1 */"

i=0
while test $i -le $max ; do 
	echo -n "	case $i: return smfi_setmlreply(ctx, rcode, xcode";
	j=0
	while test $j -le $i ; do
		echo -n ", args[$j]"
		j=$(( $j + 1 ))
	done
	echo ");"	
	i=$(( $i + 1))
done
